owner: feebyapp
repo: status

sites:
  - name: Public Web
    url: https://www.feeby.app
  - name: Dashboard
    url: $URL_DASHBOARD
  - name: Email Service
    url: $URL_EMAIL_SERVICE
    method: HEAD
  - name: Identicon Service
    url: $URL_IDENTICON_SERVICE
    method: HEAD
  - name: Island CDN
    url: $URL_ISLAND_CDN
    method: HEAD
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: www.feebystatus.com
  # baseUrl: /status
  logoUrl: https://avatars.githubusercontent.com/u/132769428?s=88&v=4
  name: Feeby Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Feeby.app
      href: https://www.feeby.app
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
